sudo: false

language: go

go:
- "1.11"

git:
  depth: 1

notifications:
  email: false

before_script:
- dep ensure
- go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint

script:
- golangci-lint run
- go test -v -race ./...
