

# todo: make happen
# [confg.sources.etcd.config]
# host = '0.0.0.0'
# port = 2379


[base]
source = "empty"

  [base.defaults]
  server_mode = 'prod'
  host = "0.0.0.0"
  port = 9090
  amqp_url = "amqp://guest:guest@localhost:5672/"

[shared_services]
source = "etcd"
priority = 1

  [shared_services.keys]
  amqp_url = "/confg/services/amqp/url"
  redis_url = "/confg/services/redis/url"

  [shared_services.config]
  host = '0.0.0.0'
  port = 2379


[local_dev]
source = "etcd"
priority = 2

  [local_dev.keys]
  amqp_url = "/confg/services/amqp/url"
  redis_url = "/confg/services/amqp/url"

  [local_dev.config]
  host = '0.0.0.0'
  port = 2379


[web_host]
source="env"
priority = 3

    [web_host.keys]
    host = "HOST"
    port = "PORT"

    server_mode = "SERVER_MODE"

#[prod_values]
#source="vault"
#priority = 10
#
#  [prod_values.keys]
#


